services:
  adguard:
   image:  adguard/adguardhome:latest
   container_name: adguard
   environment:
    - PGID=1000
    - PUID=1000
   ports:
    - 3000:3000/tcp
    - 53:53/tcp
    - 53:53/udp
    - 82:80/tcp
    # - 67:67/udp
    # - 853:853/tcp
   volumes:
    - /DATA/AppData/config/Adguard/Workdir:/opt/adguardhome/work
    - /DATA/AppData/config/Adguard/Conf:/opt/adguardhome/conf
   restart: unless-stopped