services:
  dash:
    image: mauricenino/dashdot:nvidia
    container_name: dash
    restart: unless-stopped
    privileged: true
    ports:
      - '84:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network,gpu'
      DASHDOT_ENABLE_CPU_TEMPS: "true"
      DASHDOT_SHOW_HOST: "true"
      DASHDOT_CUSTOM_HOST: ""
    deploy: # for GPU
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
