version: "2.0"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /DATA/AppData/config/jellyfin:/config
      - /DATA/Media:/data
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /DATA/AppData/config/qbittorrent:/config
      - /DATA:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
    # ports:
    # - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/Downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - /DATA/AppData/config/prowlarr:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
    # ports:
    # - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/config/sonarr:/config # config files
      - /DATA:/data # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
    # ports:
    # - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/config/radarr:/config # config files
      - /DATA:/data # download folder

  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
    volumes:
      - /DATA/AppData/config/nginxproxymanager:/data
      - /DATA/proxy:/etc/letsencrypt

  adguard:
   image:  adguard/adguardhome:latest
   container_name: adguard
   environment:
    - PGID=1000
    - PUID=1000
   ports:
    - 3000:3000/tcp
    - 53:53/tcp
    - 53:53/udp
    - 82:80/tcp
    # - 67:67/udp
    # - 853:853/tcp
   volumes:
    - /DATA/AppData/config/Adguard/Workdir:/opt/adguardhome/work
    - /DATA/AppData/config/Adguard/Conf:/opt/adguardhome/conf
   restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
      - SUBDOMAINS=deenee.duckdns.org
      - TOKEN=9736ad1d-27dd-4b9a-97e5-2bc673880e0b
      - LOG_FILE=false #optional
    volumes:
      - /DATA/AppData/config/duckdns:/config #optional
    ports:
     - 5353:53/tcp
     - 5353:53
    restart: unless-stopped

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapor
      - SERVERURL=deenee.duckdns.org #optional
      - SERVERPORT=51820 #optional
      - PEERS=5 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /DATA/AppData/config/wireguard:/config
      - /DATA/AppData/config/wireguard/lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /DATA/AppData/homarr/configs:/app/data/configs
      - /DATA/AppData/homarr/icons:/app/public/icons
      - /DATA/AppData/homarr/data:/data
    # ports:
    #  - '7575:7575'
