IG
FB
Anki
Atome
Bitwarden
Carousell
ChatGPT
DBS
Firefox
Flow
Grab + Driver
HealthHub
Headphone (sony)
Link to Windows
iReal Book
Messenger
mEzee
myM1
myENV
mySIMapp
NETSapp
Parking
Shopee
Singpass
Spotify
TribeCar
Timetree
Tiktok
Tabs
Whatsapp
Steam
ValueClub
VLC
WirelessSG
Youtrip
Waze
Pillars
X
Vance YT
McDonalds
Infiinity Reddit

Google
Docs, Sheets, Slides
Meet
Driver
Photos
Calendar
Gmail
Google One
Keep
Maps
Tasks
Rewards

Games
Human Resource Machine
Limbo
Mini Metro
Papers Please
Pirates Outlaw
Vampire Survivor