services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
      - SUBDOMAINS=deenee.duckdns.org
      - TOKEN=9736ad1d-27dd-4b9a-97e5-2bc673880e0b
      - LOG_FILE=false #optional
    volumes:
      - /DATA/AppData/config/duckdns:/config #optional
    restart: unless-stopped