services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - /:/srv
      - /DATA/AppData/config/filebrowser/filebrowser.db:/database.db
      - /DATA/AppData/config/filebrowser/settings.json:/settings.json
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true