services:
  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole
    volumes:
      - /DATA/AppData/config/guacd:/config
    ports:
      - 8787:8080
volumes:
  postgres:
    driver: local