services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /DATA/AppData/config/homarr/configs:/app/data/configs
      - /DATA/AppData/config/homarr/icons:/app/public/icons
      - /DATA/AppData/config/homarr/data:/data
    # ports:
    #  - '7575:7575'