services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - /DATA/AppData/config/jellyseerr:/app/config
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped