services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
    # ports:
    # - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/Downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - /DATA/AppData/config/prowlarr:/config # config files