services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
    # ports:
    # - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/config/radarr:/config # config files
      - /DATA:/data # download folder