services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Asia/Singapore # timezone, defined in .env
    # ports:
    # - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/config/sonarr:/config # config files
      - /DATA:/data # download folder