services:
    vaultwarden:
        container_name: vaultwarden
        volumes:
            - /DATA/AppData/config/vaultwarden:/data/
        restart: unless-stopped
        ports:
            - 8181:80
        image: vaultwarden/server:latest